import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Become a host",
	description: "Generated by create next app",
};

export default function BecomeAHostLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return <>{children}</>;
}
